# Generated by Django 4.0.2 on 2022-02-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_image_alter_post_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
